name: Validate

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-validate"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [24.x]
        os: [ubuntu-24.04]

    env:
      NEXT_PUBLIC_API_BASE_URL: "${{ vars.NEXT_PUBLIC_API_BASE_URL }}"
      NEXT_PUBLIC_API_OPENAPI_PATHNAME: "${{ vars.NEXT_PUBLIC_API_OPENAPI_PATHNAME }}"
      NEXT_PUBLIC_APP_BASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_BOTS: "disabled"
      NEXT_PUBLIC_APP_IMPRINT_CUSTOM_CONFIG: "disabled"
      NEXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL:
        "${{ vars.NEXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL }}"
      NEXT_PUBLIC_APP_MATOMO_BASE_URL: "${{ vars.NEXT_PUBLIC_APP_MATOMO_BASE_URL }}"
      NEXT_PUBLIC_APP_MATOMO_ID: "${{ vars.NEXT_PUBLIC_APP_MATOMO_ID }}"
      NEXT_PUBLIC_APP_SERVICE_ID: "${{ vars.SERVICE_ID }}"
      NEXT_PUBLIC_TYPESENSE_HOST: "localhost"
      NEXT_PUBLIC_TYPESENSE_PORT: "8108"
      NEXT_PUBLIC_TYPESENSE_PROTOCOL: "http"
      NEXT_PUBLIC_TYPESENSE_RESOURCE_COLLECTION_NAME: "dariah-resources"
      TYPESENSE_ADMIN_API_KEY: "31308e18f81519edfc65c4293c209e24ee7044d6a84251c22b15210b90b0496a"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      # - name: Test
      #   run: pnpm run test

      - name: Get playwright version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --json | jq --raw-output '.[0].devDependencies["@playwright/test"].version')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright browsers
        uses: actions/cache@v5
        id: cache-playwright-browsers
        with:
          path: "~/.cache/ms-playwright"
          key:
            "${{ matrix.os }}-${{ matrix.node-version }}-playwright-browsers-${{
            env.PLAYWRIGHT_VERSION }}"

      - name: Install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Install playwright browsers (operating system dependencies)
        if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps

      # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - name: Cache Next.js build output
        uses: actions/cache@v5
        with:
          path: "${{ github.workspace }}/.next/cache"
          key:
            "${{ matrix.os }}-${{ matrix.node-version }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}"

      - name: Start typesense server and populate search index
        run: |
          touch .env.local
          pnpm run dev:services:up
          echo "Waiting for Typesense to be ready..."
          until curl -s -o /dev/null -w "%{http_code}" -H "X-TYPESENSE-API-KEY: $TYPESENSE-API-KEY" http://localhost:8108/health | grep -q 200; do
            echo -n "."
            sleep 1
          done
          pnpm run search-index:collections:create
          pnpm run search-index:collections:seed
          echo NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY=$(pnpm run search-index:api-keys:generate | awk -F'"' '{print $2}') >> $GITHUB_ENV

      - name: Build app
        run: pnpm run build

      - name: Run e2e tests
        run: pnpm run test:e2e

      - name: Stop typesense server
        run: pnpm run dev:services:down

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
